export const TELEMETRY_DISABLED_ENVIRONMENT_VARIABLE = "JUMBO_TELEMETRY_DISABLED";

export const CI_ENVIRONMENT_VARIABLE_NAMES = [
  "CI",
  "GITHUB_ACTIONS",
  "GITLAB_CI",
  "JENKINS_URL",
  "CIRCLECI",
  "TRAVIS",
  "BUILDKITE",
] as const;
